spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/toy
    driver-class-name: org.mariadb.jdbc.Driver
    username: toy_user
    password: 1111

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ssunju5402@gmail.com
    password: kdagndtpduuwfmxk
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
