
spring:
  profiles:
    include: secret

  datasource:
    url: jdbc:mariadb://localhost:3306/toy
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  jwt:
    secret:

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kakao:
  key: